// packages/vue-todo/src/components/TodoList.vue
<template>
  <div>
    <header class="header">
      <h1>Todos</h1>
      <Can I="create" a="Todo">
        <NewTodo @submit="addTodo" />
      </Can>
    </header>
    <TodoItems
      :items="todos"
      @update="updateTodo"
      @remove="removeTodo"
    />
    <TodoFooter :items="todos" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import TodoItems, { UpdateEvent } from './TodoItems.vue';
import TodoFooter from './TodoFooter.vue';
import NewTodo from './NewTodo.vue';
import { Todo } from '../models/Todo';
import storage from '../services/todo-storage';

interface State {
  todos: Todo[]
}

export default Vue.extend({
  name: 'TodoList',
  components: {
    TodoItems,
    TodoFooter,
    NewTodo,
  },
  data: (): State => ({
    todos: [],
  }),
  watch: {
    todos: {
      deep: true,
      handler: todos => storage.save(todos)
    }
  },
  created() {
    this.todos = storage.fetch();
  },
  methods: {
    addTodo(todo: Todo) {
      this.todos.push(storage.build(todo))
    },
    updateTodo({ index, patch }: UpdateEvent) {
      Object.assign(this.todos[index], patch);
    },
    removeTodo(todo: Todo) {
      this.todos.splice(this.todos.indexOf(todo), 1)
    },
  },
});
</script>

// packages/react-todo/src/components/TodoList.tsx
import React, { Component } from 'react';
import todoStorage, { Todo } from '../services/todo-storage';
import NewTodo from './NewTodo';
import TodoListRenderer from './TodoListRenderer';
import TodoFooter from './TodoFooter';
import Can from './Can';

type State = {
  items: Todo[]
}

export default class TodoList extends Component<{}, State> {
  state = {
    items: todoStorage.fetch()
  };

  componentDidUpdate() {
    todoStorage.save(this.state.items);
  }

  private _addTodo = (attrs: Pick<Todo, 'assignee' | 'title'>) => {
    const todo = todoStorage.build(attrs)

    this.setState((prevState) => ({
      items: prevState.items.concat(todo)
    }))
  }

  private _removeTodo = (todo: Todo) => {
    this.setState((prevState) => ({
      items: prevState.items.filter(item => item !== todo)
    }))
  }

  private _editTodo = (todo: Todo) => {
    this.setState((prevState) => {
      const items = prevState.items.slice(0);
      const index = items.findIndex(item => item.id === todo.id);

      items.splice(index, 1, todo);

      return { items }
    });
  }

  private _completeTodo = (todo: Todo, completed: boolean) => {
    this.setState((prevState) => {
      const items = prevState.items.slice(0);
      const index = items.findIndex(item => item.id === todo.id);
      items[index] = { ...items[index], completed };
      return { items };
    });
  }

  render() {
    return (
      <div>
        <header className="header">
          <h1>Todos</h1>
          <Can do="create" on="Todo">
            <NewTodo onNewTodo={this._addTodo} />
          </Can>
        </header>
        <TodoListRenderer
          items={this.state.items}
          onRemove={this._removeTodo}
          onEdited={this._editTodo}
          onComplete={this._completeTodo}
          />
        <TodoFooter items={this.state.items} />
      </div>
    )
  }
}
