// packages/react-todo/src/components/TodoFooter.tsx
import React, { PureComponent } from 'react';
import { Todo } from '../services/todo-storage';
import { AbilityContext } from './Can';
import defineRulesFor from '../config/ability';

type Props = {
  items: Todo[]
};
type State = {
  role: string
};

const hint = 'Admin - can do anything.\nMember can read everything and manage todos with assignee "me"';

export default class TodoFooter extends PureComponent<Props, State> {
  static contextType = AbilityContext;

  state = {
    role: 'member'
  };

  get remaining() {
    return this.props.items.filter(item => !item.completed).length;
  }

  private _selectedIfRole(role: string) {
    return this.state.role === role ? 'selected' : '';
  }

  private _setRole(role: string) {
    this.context.update(defineRulesFor(role));
    this.setState({ role });
  }

  render() {
    return (
      <footer className="footer">
        <span className="todo-count"><b>{this.remaining}</b> left</span>
        <ul className="filters">
          <li className="help" title={hint}>Switch roles:</li>
          <li>
            <button type="button" className={this._selectedIfRole('admin')} onClick={this._setRole.bind(this, 'admin')}>
              Admin
            </button>
          </li>
          <li>
            <button type="button" className={this._selectedIfRole('member')} onClick={this._setRole.bind(this, 'member')}>
              Member
            </button>
          </li>
        </ul>
      </footer>
    )
  }
};

// packages/vue-todo/src/components/TodoFooter.vue
<template>
  <footer class="footer">
    <span class="todo-count">
      <strong>{{ remaining }}</strong> left
    </span>
    <ul class="filters">
      <li class="help" title="Admin - can do anything. Member can read everything and manage todos with assignee 'me'">Switch roles</li>
      <li><button type="button" :class="{ selected: role === 'admin' }" @click="setRole('admin')">Admin</button></li>
      <li><button type="button" :class="{ selected: role === 'member' }" @click="setRole('member')">Member</button></li>
    </ul>
  </footer>
</template>

<script lang="ts">
import Vue from 'vue';
import { defineRulesFor } from '../config/ability';
import { Todo } from '../models/Todo';

export default Vue.extend({
  name: 'TodoFooter',
  props: {
    items: {
      type: Array as () => Todo[],
      required: true,
    }
  },
  data: () => ({
    role: 'member'
  }),
  computed: {
    remaining(): number {
      return this.items.filter(item => !item.completed).length;
    },
  },
  methods: {
    setRole(role: string) {
      this.role = role;
      this.$ability.update(defineRulesFor(role));
    }
  },
});
</script>
